import type { BlogPost, Debate, Team, User } from "@/types";

export const allUsers: User[] = [
  {
    id: 1,
    name: "Alice Smith",
    email: "alice@example.com",
    role: "admin",
    status: "active",
    avatar_url: "https://i.pravatar.cc/150?img=1",
    phone: "+31612345678",
    points: 1200,
    livekit_token: null,
    email_verified_at: new Date().toISOString(),
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 2,
    name: "Bob Davis",
    email: "bob@example.com",
    role: "debater",
    status: "suspended",
    avatar_url: "https://i.pravatar.cc/150?img=2",
    phone: "+31687654321",
    points: 2450,
    livekit_token: "token_bob_123",
    email_verified_at: new Date().toISOString(),
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 3,
    name: "Charlie Wilson",
    email: "charlie@example.com",
    role: "debater",
    status: "banned",
    avatar_url: "https://i.pravatar.cc/150?img=3",
    phone: null,
    points: 300,
    livekit_token: null,
    email_verified_at: null,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 4,
    name: "Diana Lee",
    email: "diana@example.com",
    role: "trainer",
    status: "active",
    avatar_url: "https://i.pravatar.cc/150?img=4",
    phone: "+31611223344",
    points: 5000,
    livekit_token: "token_admin_456",
    email_verified_at: new Date().toISOString(),
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 5,
    name: "Ethan Moore",
    email: "ethan@example.com",
    role: "debater",
    status: "suspended",
    avatar_url: "https://i.pravatar.cc/150?img=5",
    phone: null,
    points: 150,
    livekit_token: null,
    email_verified_at: new Date().toISOString(),
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 6,
    name: "Fiona Taylor",
    email: "fiona@example.com",
    role: "debater",
    status: "active",
    avatar_url: null, // test fallback avatar in UI
    phone: "+31699887766",
    points: 980,
    livekit_token: null,
    email_verified_at: new Date().toISOString(),
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
];

export const allDebates: Debate[] = [
  {
    id: 1,
    format_id: 1,
    motion_id: 101,
    created_by: 1,
    title: "The Future of AI in Education",
    tag: "tech",
    description:
      "Exploring how artificial intelligence can transform learning.",
    status: "live", // must match DebateStatus enum
    livekit_room_name: "room-ai-1",
    recording_url: null,
    transcript: null,
    scheduled_at: new Date().toISOString(),
    started_at: new Date().toISOString(),
    ended_at: null,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 2,
    format_id: 1,
    motion_id: 102,
    created_by: 2,
    title: "Sustainable Development Goals",
    tag: "work",
    description: "Progress and challenges in SDGs.",
    status: "scheduled",
    livekit_room_name: "room-sdg-1",
    recording_url: null,
    transcript: null,
    scheduled_at: new Date().toISOString(),
    started_at: null,
    ended_at: null,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
];

export const allBlogs: BlogPost[] = [
  {
    id: 1,
    author_id: 101,
    title: "Why Rust is Taking Over Systems Programming in 2025",
    slug: "rust-systems-2025",
    content:
      "Memory safety without a garbage collector, blazing-fast performance, and an ecosystem that's quietly eaten C++'s lunch.",
    status: "published",
    cover_image_url:
      "https://images.unsplash.com/photo-1555066931-4365d14bab8c?w=400&q=80",
    reviewer_comment: null,
    published_at: new Date().toISOString(),
    created_at: new Date(Date.now() - 3 * 3600 * 1000).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 2,
    author_id: 102,
    title:
      "The Art of Saying No: How Top Designers Set Boundaries with Stakeholders",
    slug: "design-boundaries",
    content:
      "Endless revision cycles, scope creep, and death by committee. A senior designer's brutally honest guide.",
    status: "published",
    cover_image_url:
      "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=400&q=80",
    reviewer_comment: null,
    published_at: new Date().toISOString(),
    created_at: new Date(Date.now() - 6 * 3600 * 1000).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 3,
    author_id: 103,
    title:
      "I Replaced My Entire Backend with Edge Functions — Here's What Happened",
    slug: "edge-functions-backend",
    content:
      "After six months running a production app purely on edge compute, I have thoughts.",
    status: "published",
    cover_image_url:
      "https://images.unsplash.com/photo-1451187580459-43490279c0fa?w=400&q=80",
    reviewer_comment: null,
    published_at: new Date().toISOString(),
    created_at: new Date(Date.now() - 1 * 3600 * 1000).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 4,
    author_id: 104,
    title: "Dark Patterns in 2025: They Got Worse, Not Better",
    slug: "dark-patterns-2025",
    content:
      "Manipulative UX patterns have evolved — they're just harder to spot now.",
    status: "published",
    cover_image_url: null,
    reviewer_comment: null,
    published_at: new Date().toISOString(),
    created_at: new Date(Date.now() - 2 * 3600 * 1000).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 5,
    author_id: 105,
    title: "Building a Compiler From Scratch: Month 3 Update",
    slug: "compiler-month-3",
    content:
      "Code gen is finally working, but debugging register allocation was painful.",
    status: "published",
    cover_image_url:
      "https://images.unsplash.com/photo-1516116216624-53e697fedbea?w=400&q=80",
    reviewer_comment: null,
    published_at: new Date().toISOString(),
    created_at: new Date(Date.now() - 3 * 3600 * 1000).toISOString(),
    updated_at: new Date().toISOString(),
  },
];

export const allTeams: Team[] = [
  {
    id: 1,
    name: "W",
    is_random: false,
    leader_id: 6,
    created_by: 6,
    status: "active",
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 2,
    name: "L",
    is_random: true,
    leader_id: 4,
    created_by: 4,
    status: "active",
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 3,
    name: "N",
    is_random: false,
    leader_id: 3,
    created_by: 3,
    status: "inactive",
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 4,
    name: "M",
    is_random: true,
    leader_id: 1,
    created_by: 1,
    status: "active",
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 5,
    name: "A",
    is_random: false,
    leader_id: 2,
    created_by: 2,
    status: "active",
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 6,
    name: "Q",
    is_random: true,
    leader_id: 1,
    created_by: 1,
    status: "inactive",
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 7,
    name: "F",
    is_random: false,
    leader_id: 6,
    created_by: 6,
    status: "active",
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 8,
    name: "D",
    is_random: true,
    leader_id: 108,
    created_by: 108,
    status: "active",
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
];
