/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/_dashboard'
import { Route as DashboardIndexRouteImport } from './routes/_dashboard/index'
import { Route as DashboardUsersRouteImport } from './routes/_dashboard/users'
import { Route as DashboardTeamsRouteImport } from './routes/_dashboard/teams'
import { Route as DashboardSurveysRouteImport } from './routes/_dashboard/surveys'
import { Route as DashboardStatisticsRouteImport } from './routes/_dashboard/statistics'
import { Route as DashboardSettingsRouteImport } from './routes/_dashboard/settings'
import { Route as DashboardDebatesRouteImport } from './routes/_dashboard/debates'
import { Route as DashboardDebateMotionsRouteImport } from './routes/_dashboard/debate-motions'
import { Route as DashboardDebateMotionFrameworksRouteImport } from './routes/_dashboard/debate-motion-frameworks'
import { Route as DashboardDebateFormatsRouteImport } from './routes/_dashboard/debate-formats'
import { Route as DashboardComplaintsRouteImport } from './routes/_dashboard/complaints'
import { Route as DashboardBlogsRouteImport } from './routes/_dashboard/blogs'
import { Route as DashboardUsersIndexRouteImport } from './routes/_dashboard/users/index'
import { Route as DashboardSurveysIndexRouteImport } from './routes/_dashboard/surveys/index'
import { Route as DashboardDebatesIndexRouteImport } from './routes/_dashboard/debates/index'
import { Route as DashboardComplaintsIndexRouteImport } from './routes/_dashboard/complaints/index'
import { Route as DashboardUsersUserIdRouteImport } from './routes/_dashboard/users/$userId'
import { Route as DashboardSurveysSurveyIdRouteImport } from './routes/_dashboard/surveys/$surveyId'
import { Route as DashboardDebatesDebateIdRouteImport } from './routes/_dashboard/debates/$debateId'
import { Route as DashboardComplaintsComplaintIdRouteImport } from './routes/_dashboard/complaints/$complaintId'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/_dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardUsersRoute = DashboardUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardTeamsRoute = DashboardTeamsRouteImport.update({
  id: '/teams',
  path: '/teams',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSurveysRoute = DashboardSurveysRouteImport.update({
  id: '/surveys',
  path: '/surveys',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardStatisticsRoute = DashboardStatisticsRouteImport.update({
  id: '/statistics',
  path: '/statistics',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardDebatesRoute = DashboardDebatesRouteImport.update({
  id: '/debates',
  path: '/debates',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardDebateMotionsRoute = DashboardDebateMotionsRouteImport.update({
  id: '/debate-motions',
  path: '/debate-motions',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardDebateMotionFrameworksRoute =
  DashboardDebateMotionFrameworksRouteImport.update({
    id: '/debate-motion-frameworks',
    path: '/debate-motion-frameworks',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardDebateFormatsRoute = DashboardDebateFormatsRouteImport.update({
  id: '/debate-formats',
  path: '/debate-formats',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardComplaintsRoute = DashboardComplaintsRouteImport.update({
  id: '/complaints',
  path: '/complaints',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardBlogsRoute = DashboardBlogsRouteImport.update({
  id: '/blogs',
  path: '/blogs',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardUsersIndexRoute = DashboardUsersIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardUsersRoute,
} as any)
const DashboardSurveysIndexRoute = DashboardSurveysIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardSurveysRoute,
} as any)
const DashboardDebatesIndexRoute = DashboardDebatesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardDebatesRoute,
} as any)
const DashboardComplaintsIndexRoute =
  DashboardComplaintsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => DashboardComplaintsRoute,
  } as any)
const DashboardUsersUserIdRoute = DashboardUsersUserIdRouteImport.update({
  id: '/$userId',
  path: '/$userId',
  getParentRoute: () => DashboardUsersRoute,
} as any)
const DashboardSurveysSurveyIdRoute =
  DashboardSurveysSurveyIdRouteImport.update({
    id: '/$surveyId',
    path: '/$surveyId',
    getParentRoute: () => DashboardSurveysRoute,
  } as any)
const DashboardDebatesDebateIdRoute =
  DashboardDebatesDebateIdRouteImport.update({
    id: '/$debateId',
    path: '/$debateId',
    getParentRoute: () => DashboardDebatesRoute,
  } as any)
const DashboardComplaintsComplaintIdRoute =
  DashboardComplaintsComplaintIdRouteImport.update({
    id: '/$complaintId',
    path: '/$complaintId',
    getParentRoute: () => DashboardComplaintsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/login': typeof LoginRoute
  '/blogs': typeof DashboardBlogsRoute
  '/complaints': typeof DashboardComplaintsRouteWithChildren
  '/debate-formats': typeof DashboardDebateFormatsRoute
  '/debate-motion-frameworks': typeof DashboardDebateMotionFrameworksRoute
  '/debate-motions': typeof DashboardDebateMotionsRoute
  '/debates': typeof DashboardDebatesRouteWithChildren
  '/settings': typeof DashboardSettingsRoute
  '/statistics': typeof DashboardStatisticsRoute
  '/surveys': typeof DashboardSurveysRouteWithChildren
  '/teams': typeof DashboardTeamsRoute
  '/users': typeof DashboardUsersRouteWithChildren
  '/': typeof DashboardIndexRoute
  '/complaints/$complaintId': typeof DashboardComplaintsComplaintIdRoute
  '/debates/$debateId': typeof DashboardDebatesDebateIdRoute
  '/surveys/$surveyId': typeof DashboardSurveysSurveyIdRoute
  '/users/$userId': typeof DashboardUsersUserIdRoute
  '/complaints/': typeof DashboardComplaintsIndexRoute
  '/debates/': typeof DashboardDebatesIndexRoute
  '/surveys/': typeof DashboardSurveysIndexRoute
  '/users/': typeof DashboardUsersIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/blogs': typeof DashboardBlogsRoute
  '/debate-formats': typeof DashboardDebateFormatsRoute
  '/debate-motion-frameworks': typeof DashboardDebateMotionFrameworksRoute
  '/debate-motions': typeof DashboardDebateMotionsRoute
  '/settings': typeof DashboardSettingsRoute
  '/statistics': typeof DashboardStatisticsRoute
  '/teams': typeof DashboardTeamsRoute
  '/': typeof DashboardIndexRoute
  '/complaints/$complaintId': typeof DashboardComplaintsComplaintIdRoute
  '/debates/$debateId': typeof DashboardDebatesDebateIdRoute
  '/surveys/$surveyId': typeof DashboardSurveysSurveyIdRoute
  '/users/$userId': typeof DashboardUsersUserIdRoute
  '/complaints': typeof DashboardComplaintsIndexRoute
  '/debates': typeof DashboardDebatesIndexRoute
  '/surveys': typeof DashboardSurveysIndexRoute
  '/users': typeof DashboardUsersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_dashboard': typeof DashboardRouteWithChildren
  '/login': typeof LoginRoute
  '/_dashboard/blogs': typeof DashboardBlogsRoute
  '/_dashboard/complaints': typeof DashboardComplaintsRouteWithChildren
  '/_dashboard/debate-formats': typeof DashboardDebateFormatsRoute
  '/_dashboard/debate-motion-frameworks': typeof DashboardDebateMotionFrameworksRoute
  '/_dashboard/debate-motions': typeof DashboardDebateMotionsRoute
  '/_dashboard/debates': typeof DashboardDebatesRouteWithChildren
  '/_dashboard/settings': typeof DashboardSettingsRoute
  '/_dashboard/statistics': typeof DashboardStatisticsRoute
  '/_dashboard/surveys': typeof DashboardSurveysRouteWithChildren
  '/_dashboard/teams': typeof DashboardTeamsRoute
  '/_dashboard/users': typeof DashboardUsersRouteWithChildren
  '/_dashboard/': typeof DashboardIndexRoute
  '/_dashboard/complaints/$complaintId': typeof DashboardComplaintsComplaintIdRoute
  '/_dashboard/debates/$debateId': typeof DashboardDebatesDebateIdRoute
  '/_dashboard/surveys/$surveyId': typeof DashboardSurveysSurveyIdRoute
  '/_dashboard/users/$userId': typeof DashboardUsersUserIdRoute
  '/_dashboard/complaints/': typeof DashboardComplaintsIndexRoute
  '/_dashboard/debates/': typeof DashboardDebatesIndexRoute
  '/_dashboard/surveys/': typeof DashboardSurveysIndexRoute
  '/_dashboard/users/': typeof DashboardUsersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/login'
    | '/blogs'
    | '/complaints'
    | '/debate-formats'
    | '/debate-motion-frameworks'
    | '/debate-motions'
    | '/debates'
    | '/settings'
    | '/statistics'
    | '/surveys'
    | '/teams'
    | '/users'
    | '/'
    | '/complaints/$complaintId'
    | '/debates/$debateId'
    | '/surveys/$surveyId'
    | '/users/$userId'
    | '/complaints/'
    | '/debates/'
    | '/surveys/'
    | '/users/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/blogs'
    | '/debate-formats'
    | '/debate-motion-frameworks'
    | '/debate-motions'
    | '/settings'
    | '/statistics'
    | '/teams'
    | '/'
    | '/complaints/$complaintId'
    | '/debates/$debateId'
    | '/surveys/$surveyId'
    | '/users/$userId'
    | '/complaints'
    | '/debates'
    | '/surveys'
    | '/users'
  id:
    | '__root__'
    | '/_dashboard'
    | '/login'
    | '/_dashboard/blogs'
    | '/_dashboard/complaints'
    | '/_dashboard/debate-formats'
    | '/_dashboard/debate-motion-frameworks'
    | '/_dashboard/debate-motions'
    | '/_dashboard/debates'
    | '/_dashboard/settings'
    | '/_dashboard/statistics'
    | '/_dashboard/surveys'
    | '/_dashboard/teams'
    | '/_dashboard/users'
    | '/_dashboard/'
    | '/_dashboard/complaints/$complaintId'
    | '/_dashboard/debates/$debateId'
    | '/_dashboard/surveys/$surveyId'
    | '/_dashboard/users/$userId'
    | '/_dashboard/complaints/'
    | '/_dashboard/debates/'
    | '/_dashboard/surveys/'
    | '/_dashboard/users/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  DashboardRoute: typeof DashboardRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboard': {
      id: '/_dashboard'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboard/': {
      id: '/_dashboard/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/users': {
      id: '/_dashboard/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof DashboardUsersRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/teams': {
      id: '/_dashboard/teams'
      path: '/teams'
      fullPath: '/teams'
      preLoaderRoute: typeof DashboardTeamsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/surveys': {
      id: '/_dashboard/surveys'
      path: '/surveys'
      fullPath: '/surveys'
      preLoaderRoute: typeof DashboardSurveysRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/statistics': {
      id: '/_dashboard/statistics'
      path: '/statistics'
      fullPath: '/statistics'
      preLoaderRoute: typeof DashboardStatisticsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/settings': {
      id: '/_dashboard/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof DashboardSettingsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/debates': {
      id: '/_dashboard/debates'
      path: '/debates'
      fullPath: '/debates'
      preLoaderRoute: typeof DashboardDebatesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/debate-motions': {
      id: '/_dashboard/debate-motions'
      path: '/debate-motions'
      fullPath: '/debate-motions'
      preLoaderRoute: typeof DashboardDebateMotionsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/debate-motion-frameworks': {
      id: '/_dashboard/debate-motion-frameworks'
      path: '/debate-motion-frameworks'
      fullPath: '/debate-motion-frameworks'
      preLoaderRoute: typeof DashboardDebateMotionFrameworksRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/debate-formats': {
      id: '/_dashboard/debate-formats'
      path: '/debate-formats'
      fullPath: '/debate-formats'
      preLoaderRoute: typeof DashboardDebateFormatsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/complaints': {
      id: '/_dashboard/complaints'
      path: '/complaints'
      fullPath: '/complaints'
      preLoaderRoute: typeof DashboardComplaintsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/blogs': {
      id: '/_dashboard/blogs'
      path: '/blogs'
      fullPath: '/blogs'
      preLoaderRoute: typeof DashboardBlogsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/users/': {
      id: '/_dashboard/users/'
      path: '/'
      fullPath: '/users/'
      preLoaderRoute: typeof DashboardUsersIndexRouteImport
      parentRoute: typeof DashboardUsersRoute
    }
    '/_dashboard/surveys/': {
      id: '/_dashboard/surveys/'
      path: '/'
      fullPath: '/surveys/'
      preLoaderRoute: typeof DashboardSurveysIndexRouteImport
      parentRoute: typeof DashboardSurveysRoute
    }
    '/_dashboard/debates/': {
      id: '/_dashboard/debates/'
      path: '/'
      fullPath: '/debates/'
      preLoaderRoute: typeof DashboardDebatesIndexRouteImport
      parentRoute: typeof DashboardDebatesRoute
    }
    '/_dashboard/complaints/': {
      id: '/_dashboard/complaints/'
      path: '/'
      fullPath: '/complaints/'
      preLoaderRoute: typeof DashboardComplaintsIndexRouteImport
      parentRoute: typeof DashboardComplaintsRoute
    }
    '/_dashboard/users/$userId': {
      id: '/_dashboard/users/$userId'
      path: '/$userId'
      fullPath: '/users/$userId'
      preLoaderRoute: typeof DashboardUsersUserIdRouteImport
      parentRoute: typeof DashboardUsersRoute
    }
    '/_dashboard/surveys/$surveyId': {
      id: '/_dashboard/surveys/$surveyId'
      path: '/$surveyId'
      fullPath: '/surveys/$surveyId'
      preLoaderRoute: typeof DashboardSurveysSurveyIdRouteImport
      parentRoute: typeof DashboardSurveysRoute
    }
    '/_dashboard/debates/$debateId': {
      id: '/_dashboard/debates/$debateId'
      path: '/$debateId'
      fullPath: '/debates/$debateId'
      preLoaderRoute: typeof DashboardDebatesDebateIdRouteImport
      parentRoute: typeof DashboardDebatesRoute
    }
    '/_dashboard/complaints/$complaintId': {
      id: '/_dashboard/complaints/$complaintId'
      path: '/$complaintId'
      fullPath: '/complaints/$complaintId'
      preLoaderRoute: typeof DashboardComplaintsComplaintIdRouteImport
      parentRoute: typeof DashboardComplaintsRoute
    }
  }
}

interface DashboardComplaintsRouteChildren {
  DashboardComplaintsComplaintIdRoute: typeof DashboardComplaintsComplaintIdRoute
  DashboardComplaintsIndexRoute: typeof DashboardComplaintsIndexRoute
}

const DashboardComplaintsRouteChildren: DashboardComplaintsRouteChildren = {
  DashboardComplaintsComplaintIdRoute: DashboardComplaintsComplaintIdRoute,
  DashboardComplaintsIndexRoute: DashboardComplaintsIndexRoute,
}

const DashboardComplaintsRouteWithChildren =
  DashboardComplaintsRoute._addFileChildren(DashboardComplaintsRouteChildren)

interface DashboardDebatesRouteChildren {
  DashboardDebatesDebateIdRoute: typeof DashboardDebatesDebateIdRoute
  DashboardDebatesIndexRoute: typeof DashboardDebatesIndexRoute
}

const DashboardDebatesRouteChildren: DashboardDebatesRouteChildren = {
  DashboardDebatesDebateIdRoute: DashboardDebatesDebateIdRoute,
  DashboardDebatesIndexRoute: DashboardDebatesIndexRoute,
}

const DashboardDebatesRouteWithChildren =
  DashboardDebatesRoute._addFileChildren(DashboardDebatesRouteChildren)

interface DashboardSurveysRouteChildren {
  DashboardSurveysSurveyIdRoute: typeof DashboardSurveysSurveyIdRoute
  DashboardSurveysIndexRoute: typeof DashboardSurveysIndexRoute
}

const DashboardSurveysRouteChildren: DashboardSurveysRouteChildren = {
  DashboardSurveysSurveyIdRoute: DashboardSurveysSurveyIdRoute,
  DashboardSurveysIndexRoute: DashboardSurveysIndexRoute,
}

const DashboardSurveysRouteWithChildren =
  DashboardSurveysRoute._addFileChildren(DashboardSurveysRouteChildren)

interface DashboardUsersRouteChildren {
  DashboardUsersUserIdRoute: typeof DashboardUsersUserIdRoute
  DashboardUsersIndexRoute: typeof DashboardUsersIndexRoute
}

const DashboardUsersRouteChildren: DashboardUsersRouteChildren = {
  DashboardUsersUserIdRoute: DashboardUsersUserIdRoute,
  DashboardUsersIndexRoute: DashboardUsersIndexRoute,
}

const DashboardUsersRouteWithChildren = DashboardUsersRoute._addFileChildren(
  DashboardUsersRouteChildren,
)

interface DashboardRouteChildren {
  DashboardBlogsRoute: typeof DashboardBlogsRoute
  DashboardComplaintsRoute: typeof DashboardComplaintsRouteWithChildren
  DashboardDebateFormatsRoute: typeof DashboardDebateFormatsRoute
  DashboardDebateMotionFrameworksRoute: typeof DashboardDebateMotionFrameworksRoute
  DashboardDebateMotionsRoute: typeof DashboardDebateMotionsRoute
  DashboardDebatesRoute: typeof DashboardDebatesRouteWithChildren
  DashboardSettingsRoute: typeof DashboardSettingsRoute
  DashboardStatisticsRoute: typeof DashboardStatisticsRoute
  DashboardSurveysRoute: typeof DashboardSurveysRouteWithChildren
  DashboardTeamsRoute: typeof DashboardTeamsRoute
  DashboardUsersRoute: typeof DashboardUsersRouteWithChildren
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardBlogsRoute: DashboardBlogsRoute,
  DashboardComplaintsRoute: DashboardComplaintsRouteWithChildren,
  DashboardDebateFormatsRoute: DashboardDebateFormatsRoute,
  DashboardDebateMotionFrameworksRoute: DashboardDebateMotionFrameworksRoute,
  DashboardDebateMotionsRoute: DashboardDebateMotionsRoute,
  DashboardDebatesRoute: DashboardDebatesRouteWithChildren,
  DashboardSettingsRoute: DashboardSettingsRoute,
  DashboardStatisticsRoute: DashboardStatisticsRoute,
  DashboardSurveysRoute: DashboardSurveysRouteWithChildren,
  DashboardTeamsRoute: DashboardTeamsRoute,
  DashboardUsersRoute: DashboardUsersRouteWithChildren,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  DashboardRoute: DashboardRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
